# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_recovery.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recovery(object):
    def setupUi(self, Recovery):
        Recovery.setObjectName("Recovery")
        Recovery.resize(930, 345)
        Recovery.setMinimumSize(QtCore.QSize(930, 345))
        Recovery.setMaximumSize(QtCore.QSize(930, 345))
        Recovery.setStyleSheet("QWidget[objectName=\"Recovery\"] { background-color: #f6f7fb }")
        self.text_1 = QtWidgets.QLabel(Recovery)
        self.text_1.setGeometry(QtCore.QRect(20, 10, 901, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(99)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("font-weight: 800;\n"
"color: #383838;")
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QLabel(Recovery)
        self.text_2.setGeometry(QtCore.QRect(20, 40, 901, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(99)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("font-weight: 800;\n"
"color: #383838;")
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QLabel(Recovery)
        self.text_3.setGeometry(QtCore.QRect(20, 70, 901, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_3.setFont(font)
        self.text_3.setStyleSheet("color: #6a6a6a;")
        self.text_3.setObjectName("text_3")
        self.text_4 = QtWidgets.QLabel(Recovery)
        self.text_4.setGeometry(QtCore.QRect(20, 100, 801, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.text_4.setFont(font)
        self.text_4.setStyleSheet("color: #6a6a6a;")
        self.text_4.setText("")
        self.text_4.setObjectName("text_4")
        self.text_5 = QtWidgets.QLabel(Recovery)
        self.text_5.setGeometry(QtCore.QRect(20, 130, 901, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_5.setFont(font)
        self.text_5.setStyleSheet("color: #6a6a6a;")
        self.text_5.setText("")
        self.text_5.setObjectName("text_5")
        self.text_6 = QtWidgets.QLabel(Recovery)
        self.text_6.setGeometry(QtCore.QRect(20, 200, 901, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_6.setFont(font)
        self.text_6.setStyleSheet("color: #6a6a6a;")
        self.text_6.setText("")
        self.text_6.setObjectName("text_6")
        self.email_system = QtWidgets.QLineEdit(Recovery)
        self.email_system.setGeometry(QtCore.QRect(20, 280, 751, 51))
        self.email_system.setStyleSheet("QLineEdit[objectName=\"email_system\"] {\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 15px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 16px;\n"
"    padding-left: 1em;\n"
"}\n"
"")
        self.email_system.setObjectName("email_system")
        self.apply = QtWidgets.QPushButton(Recovery)
        self.apply.setGeometry(QtCore.QRect(810, 290, 91, 31))
        self.apply.setMinimumSize(QtCore.QSize(91, 31))
        self.apply.setMaximumSize(QtCore.QSize(91, 31))
        self.apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #3f5cde; \n"
"    background-color: #3f5cde;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #243581;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #243581; \n"
"}")
        self.apply.setObjectName("apply")
        self.error = QtWidgets.QLabel(Recovery)
        self.error.setGeometry(QtCore.QRect(20, 240, 901, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.error.setFont(font)
        self.error.setStyleSheet("color: #6a6a6a;")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")

        self.retranslateUi(Recovery)
        QtCore.QMetaObject.connectSlotsByName(Recovery)

    def retranslateUi(self, Recovery):
        _translate = QtCore.QCoreApplication.translate
        Recovery.setWindowTitle(_translate("Recovery", "Восстановление доступа"))
        self.text_1.setText(_translate("Recovery", "Восстановление доступа"))
        self.text_2.setText(_translate("Recovery", "Внимательно ознакомьтесь с пунктами ниже!"))
        self.text_3.setText(_translate("Recovery", "Восстановление доступа возможно только при наличии вашей электронной почты в нашей базе."))
        self.apply.setText(_translate("Recovery", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recovery = QtWidgets.QWidget()
    ui = Ui_Recovery()
    ui.setupUi(Recovery)
    Recovery.show()
    sys.exit(app.exec_())
