# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_JournalWindow(object):
    def setupUi(self, JournalWindow):
        JournalWindow.setObjectName("JournalWindow")
        JournalWindow.resize(1212, 707)
        self.centralwidget = QtWidgets.QWidget(JournalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        JournalWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(JournalWindow)
        QtCore.QMetaObject.connectSlotsByName(JournalWindow)

    def retranslateUi(self, JournalWindow):
        _translate = QtCore.QCoreApplication.translate
        JournalWindow.setWindowTitle(_translate("JournalWindow", "MainWindow"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    JournalWindow = QtWidgets.QMainWindow()
    ui = Ui_JournalWindow()
    ui.setupUi(JournalWindow)
    JournalWindow.show()
    sys.exit(app.exec_())
