# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 371)
        MainWindow.setStyleSheet("QWidget[objectName=\"profile_page\"],\n"
                                 "QWidget[objectName=\"journal_page\"],\n"
                                 "QWidget[objectName=\"settings_page\"],\n"
                                 "QWidget[objectName=\"help_page\"],\n"
                                 "QWidget[objectName=\"change_page\"] { background-color: #f6f8fa; }\n"
                                 "\n"
                                 "\n"
                                 "QFrame[objectName=\"main_information\"],\n"
                                 "QFrame[objectName=\"journal_choice\"],\n"
                                 "QFrame[objectName=\"change_object\"],\n"
                                 "QFrame[objectName=\"settings_program_frame\"],\n"
                                 "QFrame[objectName=\"about_program_frame\"],\n"
                                 "QFrame[objectName=\"about_me_main\"] { background-color: #ffffff }\n"
                                 "\n"
                                 "\n"
                                 "QFrame[objectName=\"navigation_bar\"] { background-color: #19202e }\n"
                                 "\n"
                                 "\n"
                                 "QFrame[objectName=\"about_me_secondary\" ] { border-top: 1px solid #f7f7f7;  border-bottom: 1px solid #f7f7f7; }\n"
                                 "\n"
                                 "\n"
                                 "QPushButton[objectName=\"profile_menu\"],\n"
                                 "QPushButton[objectName=\"journal_menu\"],\n"
                                 "QPushButton[objectName=\"settings_menu\"],\n"
                                 "QPushButton[objectName=\"help_menu\"],\n"
                                 "QPushButton[objectName=\"image_change\"],\n"
                                 "QPushButton[objectName=\"group_sync\"],\n"
                                 "QPushButton[objectName=\"semester_sync\"],\n"
                                 "QPushButton[objectName=\"subject_sync\"] { background: transparent; }\n"
                                 "\n"
                                 "\n"
                                 "QPushButton[objectName=\"settings\"] {\n"
                                 "     background: transparent;\n"
                                 "     border: 2px solid #474b51;\n"
                                 "     border-radius: 5px;\n"
                                 "     color: #474b51; \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton[objectName=\"settings\"]:hover {\n"
                                 "    border: 2px solid #474b51;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #474b51;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton[objectName=\"settings\"]:pressed {\n"
                                 "    border: 2px solid #474b51;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #474b51;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton[objectName=\"journal_open\"] {\n"
                                 "     background: transparent;\n"
                                 "     border: 1px solid #c1c3d0;\n"
                                 "     border-radius: 5px;\n"
                                 "     color: #474b51; \n"
                                 "}\n"
                                 "QPushButton[objectName=\"journal_open\"]:hover {\n"
                                 "    border: 1px solid #000000;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: transparent;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"journal_open\"]:pressed {\n"
                                 "    border: 1px solid #000000;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: transparent;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"email_change\"] {\n"
                                 "     background: transparent;\n"
                                 "     border: 2px solid #f7f7f7;\n"
                                 "     border-radius: 5px;\n"
                                 "     color: #474b51; \n"
                                 "}\n"
                                 "QPushButton[objectName=\"email_change\"]:hover {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"email_change\"]:pressed {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"password_change\"] {\n"
                                 "     background: transparent;\n"
                                 "     border: 2px solid #f7f7f7;\n"
                                 "     border-radius: 5px;\n"
                                 "     color: #474b51; \n"
                                 "}\n"
                                 "QPushButton[objectName=\"password_change\"]:hover {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"password_change\"]:pressed {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"path_db_button\"] {\n"
                                 "     background: transparent;\n"
                                 "     border: 2px solid #f7f7f7;\n"
                                 "     border-radius: 5px;\n"
                                 "     color: #474b51; \n"
                                 "}\n"
                                 "QPushButton[objectName=\"path_db_button\"]:hover {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "QPushButton[objectName=\"path_db_button\"]:pressed {\n"
                                 "    border: 2px solid #c1c3d0;\n"
                                 "    border-radius: 7px;\n"
                                 "    background-color: #c1c3d0;\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "QLabel[objectName=\"date\"] { color: #c8c8c8; }\n"
                                 "QLabel[objectName=\"institute_title\"] { color: #c8c8c8; }\n"
                                 "QLabel[objectName=\"specialization_title\"] { color: #c8c8c8; }\n"
                                 "QLabel[objectName=\"profile_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"training_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"year_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"group_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"semester_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"subject_title\"] { color: #c8c8c8 }\n"
                                 "QLabel[objectName=\"settings_user_subtitle\"],\n"
                                 "QLabel[objectName=\"about_program_subtitle\"],\n"
                                 "QLabel[objectName=\"journal_subtitle\"], QLabel[objectName=\"settings_program_subtitle\"] { color: #6c6d72 }\n"
                                 "QLabel[objectName=\"image\"] {\n"
                                 "    border-radius: 65px;\n"
                                 "    min-height: 130px;\n"
                                 "    max-height: 130px;\n"
                                 "    min-width: 130px;\n"
                                 "    max-width: 130px;\n"
                                 "    background-color: transparent;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "QLineEdit[objectName=\"email_entry\"] { border: 1px solid #f7f7f7; border-radius: 4px;}\n"
                                 "QLineEdit[objectName=\"email_entry\"]:hover { border: 1px solid #c1c3d0;  border-radius: 4px;}\n"
                                 "QLineEdit[objectName=\"password_entry\"] { border: 1px solid #f7f7f7; border-radius: 4px;}\n"
                                 "QLineEdit[objectName=\"password_entry\"]:hover { border: 1px solid #c1c3d0;  border-radius: 4px;}\n"
                                 "QLineEdit[objectName=\"path_db_line\"] { border: 1px solid #f7f7f7; border-radius: 4px;}\n"
                                 "QLineEdit[objectName=\"path_db_line\"]:hover { border: 1px solid #c1c3d0;  border-radius: 4px;}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "QComboBox {\n"
                                 "    border: 1px solid #c8c8c8;\n"
                                 "    border-radius: 3px;\n"
                                 "    padding: 1px 18px 1px 3px;\n"
                                 "    min-width: 6em;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox:editable {\n"
                                 "    background: white;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox:!editable, QComboBox::drop-down:editable {\n"
                                 "     background: white;\n"
                                 "}\n"
                                 "\n"
                                 "/* QComboBox gets the \"on\" state when the popup is open */\n"
                                 "QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
                                 "    background: white;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox:on { /* shift the text when the popup opens */\n"
                                 "    padding-top: 3px;\n"
                                 "    padding-left: 4px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox::drop-down {\n"
                                 "    subcontrol-origin: padding;\n"
                                 "    subcontrol-position: top right;\n"
                                 "    width: 15px;\n"
                                 "\n"
                                 "    border-left-width: 1px;\n"
                                 "    border-left-color: white;\n"
                                 "    border-left-style: solid; /* just a single line */\n"
                                 "    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                                 "    border-bottom-right-radius: 3px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox::down-arrow {\n"
                                 "    padding: 0px 5px 0px 0px;\n"
                                 "    image: url(D:/portal-parser/gui/icons/down-arrow.png);\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
                                 "    top: 1px;\n"
                                 "    left: 1px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox QAbstractItemView {\n"
                                 "    border: 1px solid #c8c8c8;\n"
                                 "    color: black;\n"
                                 "    selection-color: black;\n"
                                 "    selection-background-color: #c8c8c8;\n"
                                 "    min-height: 50px;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 0, 991, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.main_information = QtWidgets.QFrame(self.profile_page)
        self.main_information.setGeometry(QtCore.QRect(40, 30, 231, 311))
        self.main_information.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_information.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_information.setObjectName("main_information")
        self.image = QtWidgets.QLabel(self.main_information)
        self.image.setGeometry(QtCore.QRect(50, 30, 130, 130))
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.name = QtWidgets.QLabel(self.main_information)
        self.name.setGeometry(QtCore.QRect(0, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.group = QtWidgets.QLabel(self.main_information)
        self.group.setGeometry(QtCore.QRect(0, 210, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.group.setFont(font)
        self.group.setAlignment(QtCore.Qt.AlignCenter)
        self.group.setObjectName("group")
        self.date = QtWidgets.QLabel(self.main_information)
        self.date.setGeometry(QtCore.QRect(0, 190, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.settings = QtWidgets.QPushButton(self.main_information)
        self.settings.setGeometry(QtCore.QRect(40, 250, 151, 31))
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings.setObjectName("settings")
        self.image_change = QtWidgets.QPushButton(self.main_information)
        self.image_change.setGeometry(QtCore.QRect(200, 10, 21, 23))
        self.image_change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.image_change.setText("")
        self.image_change.setObjectName("image_change")
        self.image_icon = QtWidgets.QLabel(self.main_information)
        self.image_icon.setGeometry(QtCore.QRect(200, 10, 23, 21))
        self.image_icon.setText("")
        self.image_icon.setPixmap(QtGui.QPixmap("../icons/change_image.png"))
        self.image_icon.setScaledContents(True)
        self.image_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.image_icon.setObjectName("image_icon")
        self.image.raise_()
        self.name.raise_()
        self.group.raise_()
        self.date.raise_()
        self.settings.raise_()
        self.image_icon.raise_()
        self.image_change.raise_()
        self.about_me_main = QtWidgets.QFrame(self.profile_page)
        self.about_me_main.setGeometry(QtCore.QRect(290, 30, 671, 311))
        self.about_me_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_me_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_me_main.setObjectName("about_me_main")
        self.about_me_secondary = QtWidgets.QFrame(self.about_me_main)
        self.about_me_secondary.setGeometry(QtCore.QRect(40, 60, 591, 231))
        self.about_me_secondary.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_me_secondary.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_me_secondary.setObjectName("about_me_secondary")
        self.institute_title = QtWidgets.QLabel(self.about_me_secondary)
        self.institute_title.setGeometry(QtCore.QRect(30, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.institute_title.setFont(font)
        self.institute_title.setStyleSheet("")
        self.institute_title.setObjectName("institute_title")
        self.institute_about = QtWidgets.QLabel(self.about_me_secondary)
        self.institute_about.setGeometry(QtCore.QRect(40, 30, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setUnderline(False)
        self.institute_about.setFont(font)
        self.institute_about.setStyleSheet("")
        self.institute_about.setObjectName("institute_about")
        self.specialization_title = QtWidgets.QLabel(self.about_me_secondary)
        self.specialization_title.setGeometry(QtCore.QRect(250, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.specialization_title.setFont(font)
        self.specialization_title.setStyleSheet("")
        self.specialization_title.setObjectName("specialization_title")
        self.specialization_about = QtWidgets.QLabel(self.about_me_secondary)
        self.specialization_about.setGeometry(QtCore.QRect(260, 70, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.specialization_about.setFont(font)
        self.specialization_about.setStyleSheet("")
        self.specialization_about.setObjectName("specialization_about")
        self.profile_title = QtWidgets.QLabel(self.about_me_secondary)
        self.profile_title.setGeometry(QtCore.QRect(250, 130, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.profile_title.setFont(font)
        self.profile_title.setStyleSheet("")
        self.profile_title.setObjectName("profile_title")
        self.profile_about = QtWidgets.QLabel(self.about_me_secondary)
        self.profile_about.setGeometry(QtCore.QRect(260, 150, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.profile_about.setFont(font)
        self.profile_about.setStyleSheet("")
        self.profile_about.setObjectName("profile_about")
        self.training_title = QtWidgets.QLabel(self.about_me_secondary)
        self.training_title.setGeometry(QtCore.QRect(30, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.training_title.setFont(font)
        self.training_title.setStyleSheet("")
        self.training_title.setObjectName("training_title")
        self.training_about = QtWidgets.QLabel(self.about_me_secondary)
        self.training_about.setGeometry(QtCore.QRect(40, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.training_about.setFont(font)
        self.training_about.setStyleSheet("")
        self.training_about.setObjectName("training_about")
        self.year_title = QtWidgets.QLabel(self.about_me_secondary)
        self.year_title.setGeometry(QtCore.QRect(30, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.year_title.setFont(font)
        self.year_title.setStyleSheet("")
        self.year_title.setObjectName("year_title")
        self.year_about = QtWidgets.QLabel(self.about_me_secondary)
        self.year_about.setGeometry(QtCore.QRect(40, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.year_about.setFont(font)
        self.year_about.setStyleSheet("")
        self.year_about.setObjectName("year_about")
        self.title = QtWidgets.QLabel(self.about_me_main)
        self.title.setGeometry(QtCore.QRect(70, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.stackedWidget.addWidget(self.profile_page)
        self.journal_page = QtWidgets.QWidget()
        self.journal_page.setObjectName("journal_page")
        self.journal_choice = QtWidgets.QFrame(self.journal_page)
        self.journal_choice.setGeometry(QtCore.QRect(30, 110, 931, 241))
        self.journal_choice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.journal_choice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.journal_choice.setObjectName("journal_choice")
        self.group_choice = QtWidgets.QComboBox(self.journal_choice)
        self.group_choice.setGeometry(QtCore.QRect(50, 70, 171, 31))
        self.group_choice.setEditable(True)
        self.group_choice.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.group_choice.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        self.group_choice.setObjectName("group_choice")
        self.group_sync = QtWidgets.QPushButton(self.journal_choice)
        self.group_sync.setGeometry(QtCore.QRect(120, 120, 31, 31))
        self.group_sync.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.group_sync.setText("")
        self.group_sync.setObjectName("group_sync")
        self.semester_choice = QtWidgets.QComboBox(self.journal_choice)
        self.semester_choice.setGeometry(QtCore.QRect(390, 70, 171, 31))
        self.semester_choice.setStyleSheet("")
        self.semester_choice.setEditable(True)
        self.semester_choice.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.semester_choice.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        self.semester_choice.setObjectName("semester_choice")
        self.semester_choice.addItem("")
        self.semester_icon = QtWidgets.QLabel(self.journal_choice)
        self.semester_icon.setGeometry(QtCore.QRect(460, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.semester_icon.setFont(font)
        self.semester_icon.setStyleSheet("")
        self.semester_icon.setText("")
        self.semester_icon.setPixmap(QtGui.QPixmap("../icons/journal_semester.png"))
        self.semester_icon.setScaledContents(True)
        self.semester_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.semester_icon.setObjectName("semester_icon")
        self.subject_choice = QtWidgets.QComboBox(self.journal_choice)
        self.subject_choice.setGeometry(QtCore.QRect(710, 70, 171, 31))
        self.subject_choice.setStyleSheet("")
        self.subject_choice.setEditable(True)
        self.subject_choice.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.subject_choice.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        self.subject_choice.setObjectName("subject_choice")
        self.subject_choice.addItem("")
        self.subject_choice.addItem("")
        self.subject_sync = QtWidgets.QPushButton(self.journal_choice)
        self.subject_sync.setGeometry(QtCore.QRect(780, 120, 31, 31))
        self.subject_sync.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subject_sync.setText("")
        self.subject_sync.setObjectName("subject_sync")
        self.journal_open = QtWidgets.QPushButton(self.journal_choice)
        self.journal_open.setGeometry(QtCore.QRect(195, 190, 541, 23))
        self.journal_open.setObjectName("journal_open")
        self.subject_icon = QtWidgets.QLabel(self.journal_choice)
        self.subject_icon.setGeometry(QtCore.QRect(780, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.subject_icon.setFont(font)
        self.subject_icon.setStyleSheet("")
        self.subject_icon.setText("")
        self.subject_icon.setPixmap(QtGui.QPixmap("../icons/journal_subject.png"))
        self.subject_icon.setScaledContents(True)
        self.subject_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_icon.setObjectName("subject_icon")
        self.group_sync_icon = QtWidgets.QLabel(self.journal_choice)
        self.group_sync_icon.setGeometry(QtCore.QRect(120, 120, 31, 31))
        self.group_sync_icon.setText("")
        self.group_sync_icon.setPixmap(QtGui.QPixmap("../icons/synchronization.png"))
        self.group_sync_icon.setScaledContents(True)
        self.group_sync_icon.setObjectName("group_sync_icon")
        self.semester_sync_icon = QtWidgets.QLabel(self.journal_choice)
        self.semester_sync_icon.setGeometry(QtCore.QRect(460, 120, 31, 31))
        self.semester_sync_icon.setText("")
        self.semester_sync_icon.setPixmap(QtGui.QPixmap("../icons/synchronization.png"))
        self.semester_sync_icon.setScaledContents(True)
        self.semester_sync_icon.setObjectName("semester_sync_icon")
        self.subject_sync_icon = QtWidgets.QLabel(self.journal_choice)
        self.subject_sync_icon.setGeometry(QtCore.QRect(780, 120, 31, 31))
        self.subject_sync_icon.setText("")
        self.subject_sync_icon.setPixmap(QtGui.QPixmap("../icons/synchronization.png"))
        self.subject_sync_icon.setScaledContents(True)
        self.subject_sync_icon.setObjectName("subject_sync_icon")
        self.group_icon = QtWidgets.QLabel(self.journal_choice)
        self.group_icon.setGeometry(QtCore.QRect(120, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setUnderline(True)
        self.group_icon.setFont(font)
        self.group_icon.setStyleSheet("")
        self.group_icon.setText("")
        self.group_icon.setPixmap(QtGui.QPixmap("../icons/journal_group.png"))
        self.group_icon.setScaledContents(True)
        self.group_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.group_icon.setObjectName("group_icon")
        self.semester_sync = QtWidgets.QPushButton(self.journal_choice)
        self.semester_sync.setGeometry(QtCore.QRect(460, 120, 31, 31))
        self.semester_sync.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.semester_sync.setText("")
        self.semester_sync.setObjectName("semester_sync")
        self.group_sync_icon.raise_()
        self.subject_sync_icon.raise_()
        self.semester_sync_icon.raise_()
        self.group_choice.raise_()
        self.group_sync.raise_()
        self.semester_choice.raise_()
        self.semester_icon.raise_()
        self.subject_choice.raise_()
        self.subject_sync.raise_()
        self.journal_open.raise_()
        self.subject_icon.raise_()
        self.group_icon.raise_()
        self.semester_sync.raise_()
        self.journal_subtitle = QtWidgets.QLabel(self.journal_page)
        self.journal_subtitle.setGeometry(QtCore.QRect(60, 80, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.journal_subtitle.setFont(font)
        self.journal_subtitle.setObjectName("journal_subtitle")
        self.journal_title = QtWidgets.QLabel(self.journal_page)
        self.journal_title.setGeometry(QtCore.QRect(40, 30, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        self.journal_title.setFont(font)
        self.journal_title.setObjectName("journal_title")
        self.stackedWidget.addWidget(self.journal_page)
        self.change_page = QtWidgets.QWidget()
        self.change_page.setObjectName("change_page")
        self.change_object = QtWidgets.QFrame(self.change_page)
        self.change_object.setGeometry(QtCore.QRect(30, 110, 931, 231))
        self.change_object.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_object.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_object.setObjectName("change_object")
        self.email_icon = QtWidgets.QLabel(self.change_object)
        self.email_icon.setGeometry(QtCore.QRect(190, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setUnderline(True)
        self.email_icon.setFont(font)
        self.email_icon.setStyleSheet("")
        self.email_icon.setText("")
        self.email_icon.setPixmap(QtGui.QPixmap("../icons/change_mail.png"))
        self.email_icon.setScaledContents(True)
        self.email_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.email_icon.setObjectName("email_icon")
        self.password_entry = QtWidgets.QLineEdit(self.change_object)
        self.password_entry.setGeometry(QtCore.QRect(570, 90, 311, 41))
        self.password_entry.setObjectName("password_entry")
        self.password_icon = QtWidgets.QLabel(self.change_object)
        self.password_icon.setGeometry(QtCore.QRect(710, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setUnderline(True)
        self.password_icon.setFont(font)
        self.password_icon.setStyleSheet("")
        self.password_icon.setText("")
        self.password_icon.setPixmap(QtGui.QPixmap("../icons/key-chain.png"))
        self.password_icon.setScaledContents(True)
        self.password_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.password_icon.setObjectName("password_icon")
        self.email_entry = QtWidgets.QLineEdit(self.change_object)
        self.email_entry.setGeometry(QtCore.QRect(50, 90, 311, 41))
        self.email_entry.setObjectName("email_entry")
        self.email_change = QtWidgets.QPushButton(self.change_object)
        self.email_change.setGeometry(QtCore.QRect(160, 140, 81, 31))
        self.email_change.setObjectName("email_change")
        self.password_change = QtWidgets.QPushButton(self.change_object)
        self.password_change.setGeometry(QtCore.QRect(680, 140, 81, 31))
        self.password_change.setObjectName("password_change")
        self.settings_user_title = QtWidgets.QLabel(self.change_page)
        self.settings_user_title.setGeometry(QtCore.QRect(30, 30, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        self.settings_user_title.setFont(font)
        self.settings_user_title.setObjectName("settings_user_title")
        self.settings_user_subtitle = QtWidgets.QLabel(self.change_page)
        self.settings_user_subtitle.setGeometry(QtCore.QRect(50, 80, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.settings_user_subtitle.setFont(font)
        self.settings_user_subtitle.setObjectName("settings_user_subtitle")
        self.stackedWidget.addWidget(self.change_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.settings_program_title = QtWidgets.QLabel(self.settings_page)
        self.settings_program_title.setGeometry(QtCore.QRect(20, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        self.settings_program_title.setFont(font)
        self.settings_program_title.setObjectName("settings_program_title")
        self.settings_program_subtitle = QtWidgets.QLabel(self.settings_page)
        self.settings_program_subtitle.setGeometry(QtCore.QRect(40, 60, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.settings_program_subtitle.setFont(font)
        self.settings_program_subtitle.setObjectName("settings_program_subtitle")
        self.settings_program_frame = QtWidgets.QFrame(self.settings_page)
        self.settings_program_frame.setGeometry(QtCore.QRect(30, 90, 931, 271))
        self.settings_program_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_program_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_program_frame.setObjectName("settings_program_frame")
        self.path_db_button = QtWidgets.QPushButton(self.settings_program_frame)
        self.path_db_button.setGeometry(QtCore.QRect(420, 160, 91, 25))
        self.path_db_button.setObjectName("path_db_button")
        self.path_db_line = QtWidgets.QLineEdit(self.settings_program_frame)
        self.path_db_line.setGeometry(QtCore.QRect(300, 120, 341, 31))
        self.path_db_line.setReadOnly(False)
        self.path_db_line.setObjectName("path_db_line")
        self.db_icon = QtWidgets.QLabel(self.settings_program_frame)
        self.db_icon.setGeometry(QtCore.QRect(450, 70, 41, 41))
        self.db_icon.setText("")
        self.db_icon.setPixmap(QtGui.QPixmap("../icons/sql-server.png"))
        self.db_icon.setScaledContents(True)
        self.db_icon.setObjectName("db_icon")
        self.stackedWidget.addWidget(self.settings_page)
        self.help_page = QtWidgets.QWidget()
        self.help_page.setObjectName("help_page")
        self.about_program_title = QtWidgets.QLabel(self.help_page)
        self.about_program_title.setGeometry(QtCore.QRect(30, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        self.about_program_title.setFont(font)
        self.about_program_title.setObjectName("about_program_title")
        self.about_program_subtitle = QtWidgets.QLabel(self.help_page)
        self.about_program_subtitle.setGeometry(QtCore.QRect(50, 60, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.about_program_subtitle.setFont(font)
        self.about_program_subtitle.setObjectName("about_program_subtitle")
        self.about_program_frame = QtWidgets.QFrame(self.help_page)
        self.about_program_frame.setGeometry(QtCore.QRect(30, 90, 941, 271))
        self.about_program_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_program_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_program_frame.setObjectName("about_program_frame")
        self.developers_icon = QtWidgets.QLabel(self.about_program_frame)
        self.developers_icon.setGeometry(QtCore.QRect(850, 20, 60, 60))
        self.developers_icon.setText("")
        self.developers_icon.setPixmap(QtGui.QPixmap("../icons/mammoth_icon.png"))
        self.developers_icon.setScaledContents(True)
        self.developers_icon.setObjectName("developers_icon")
        self.developers_name = QtWidgets.QLabel(self.about_program_frame)
        self.developers_name.setGeometry(QtCore.QRect(840, 80, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.developers_name.setFont(font)
        self.developers_name.setAlignment(QtCore.Qt.AlignCenter)
        self.developers_name.setObjectName("developers_name")
        self.program_version = QtWidgets.QLabel(self.about_program_frame)
        self.program_version.setGeometry(QtCore.QRect(390, 240, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.program_version.setFont(font)
        self.program_version.setObjectName("program_version")
        self.description_program_title = QtWidgets.QLabel(self.about_program_frame)
        self.description_program_title.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.description_program_title.setFont(font)
        self.description_program_title.setObjectName("description_program_title")
        self.description_program = QtWidgets.QLabel(self.about_program_frame)
        self.description_program.setGeometry(QtCore.QRect(30, 50, 771, 171))
        self.description_program.setObjectName("description_program")
        self.stackedWidget.addWidget(self.help_page)
        self.navigation_bar = QtWidgets.QFrame(self.centralwidget)
        self.navigation_bar.setGeometry(QtCore.QRect(0, 0, 61, 371))
        self.navigation_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigation_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation_bar.setObjectName("navigation_bar")
        self.profile_menu = QtWidgets.QPushButton(self.navigation_bar)
        self.profile_menu.setGeometry(QtCore.QRect(0, 20, 61, 51))
        self.profile_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_menu.setText("")
        self.profile_menu.setObjectName("profile_menu")
        self.journal_menu = QtWidgets.QPushButton(self.navigation_bar)
        self.journal_menu.setGeometry(QtCore.QRect(0, 80, 61, 51))
        self.journal_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.journal_menu.setText("")
        self.journal_menu.setObjectName("journal_menu")
        self.settings_menu = QtWidgets.QPushButton(self.navigation_bar)
        self.settings_menu.setGeometry(QtCore.QRect(0, 140, 61, 51))
        self.settings_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_menu.setText("")
        self.settings_menu.setObjectName("settings_menu")
        self.help_menu = QtWidgets.QPushButton(self.navigation_bar)
        self.help_menu.setGeometry(QtCore.QRect(0, 200, 61, 51))
        self.help_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_menu.setText("")
        self.help_menu.setObjectName("help_menu")
        self.profile_icon = QtWidgets.QLabel(self.navigation_bar)
        self.profile_icon.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.profile_icon.setText("")
        self.profile_icon.setPixmap(QtGui.QPixmap("../icons/navbar_profile.png"))
        self.profile_icon.setScaledContents(True)
        self.profile_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_icon.setObjectName("profile_icon")
        self.journal_icon = QtWidgets.QLabel(self.navigation_bar)
        self.journal_icon.setGeometry(QtCore.QRect(10, 90, 41, 31))
        self.journal_icon.setText("")
        self.journal_icon.setPixmap(QtGui.QPixmap("../icons/navbar_journal.png"))
        self.journal_icon.setScaledContents(True)
        self.journal_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.journal_icon.setObjectName("journal_icon")
        self.settings_icon = QtWidgets.QLabel(self.navigation_bar)
        self.settings_icon.setGeometry(QtCore.QRect(10, 150, 41, 31))
        self.settings_icon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.settings_icon.setText("")
        self.settings_icon.setPixmap(QtGui.QPixmap("../icons/navbar_settings.png"))
        self.settings_icon.setScaledContents(True)
        self.settings_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_icon.setObjectName("settings_icon")
        self.help_icon = QtWidgets.QLabel(self.navigation_bar)
        self.help_icon.setGeometry(QtCore.QRect(10, 210, 41, 31))
        self.help_icon.setText("")
        self.help_icon.setPixmap(QtGui.QPixmap("../icons/navbar_help.png"))
        self.help_icon.setScaledContents(True)
        self.help_icon.setObjectName("help_icon")
        self.settings_icon.raise_()
        self.profile_icon.raise_()
        self.journal_icon.raise_()
        self.help_icon.raise_()
        self.profile_menu.raise_()
        self.journal_menu.raise_()
        self.settings_menu.raise_()
        self.help_menu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Башков Денис"))
        self.group.setText(_translate("MainWindow", "П2-19"))
        self.date.setText(_translate("MainWindow", "23.09.2003"))
        self.settings.setText(_translate("MainWindow", "Настройки"))
        self.institute_title.setText(_translate("MainWindow", "Институт:"))
        self.institute_about.setText(_translate("MainWindow", "Программирование"))
        self.specialization_title.setText(_translate("MainWindow", "Специальность:"))
        self.specialization_about.setText(_translate("MainWindow", "Программирование в компьютерных системах"))
        self.profile_title.setText(_translate("MainWindow", "Профиль / специализация / направленность:"))
        self.profile_about.setText(_translate("MainWindow", "Нет"))
        self.training_title.setText(_translate("MainWindow", "Период обучения:"))
        self.training_about.setText(_translate("MainWindow", "3 года 10 мес."))
        self.year_title.setText(_translate("MainWindow", "Год поступления:"))
        self.year_about.setText(_translate("MainWindow", "2019"))
        self.title.setText(_translate("MainWindow", "Обо мне"))
        self.group_choice.setItemText(0, _translate("MainWindow", "Выберите группу"))
        self.group_choice.setItemText(1, _translate("MainWindow", "П1-19"))
        self.group_choice.setItemText(2, _translate("MainWindow", "П2-19"))
        self.group_choice.setItemText(3, _translate("MainWindow", "П3-19"))
        self.semester_choice.setItemText(0, _translate("MainWindow", "Выберите семестр"))
        self.subject_choice.setItemText(0, _translate("MainWindow", "Выберите предмет"))
        self.subject_choice.setItemText(1, _translate("MainWindow", "П2-19"))
        self.journal_open.setText(_translate("MainWindow", "Открыть Журнал"))
        self.journal_subtitle.setText(_translate("MainWindow", "Выбор параметров"))
        self.journal_title.setText(_translate("MainWindow", "Журнал"))
        self.password_entry.setPlaceholderText(_translate("MainWindow", "Введите новый пароль"))
        self.email_entry.setText(_translate("MainWindow", "denis170.170@gmail.com"))
        self.email_change.setText(_translate("MainWindow", "Изменить"))
        self.password_change.setText(_translate("MainWindow", "Изменить"))
        self.settings_user_title.setText(_translate("MainWindow", "Настройки аккаунта"))
        self.settings_user_subtitle.setText(_translate("MainWindow", "Смена почты и пароля"))
        self.settings_program_title.setText(_translate("MainWindow", "Настройки программы"))
        self.settings_program_subtitle.setText(
            _translate("MainWindow", "Изменение настроек в соответствии с нуждами пользователя"))
        self.path_db_button.setText(_translate("MainWindow", "Выбрать файл"))
        self.path_db_line.setPlaceholderText(_translate("MainWindow", "Полный путь до БД"))
        self.about_program_title.setText(_translate("MainWindow", "О программе"))
        self.about_program_subtitle.setText(_translate("MainWindow", "Краткая информация о программе"))
        self.developers_name.setText(_translate("MainWindow", "modern."))
        self.program_version.setText(_translate("MainWindow", "Версия программы: alpha"))
        self.description_program_title.setText(_translate("MainWindow", "Описание программы"))
        self.description_program.setText(_translate("MainWindow",
                                                    "------------------------------------------------------------------------------------------------------------------------------------------"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
