# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1225, 458)
        Main.setStyleSheet("QWidget[objectName=\"Main\"] { background-color: #f0f8ff; border: none}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Main)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane { border: none; }\n"
"QTabWidget::tab-bar { alignment: centre; }")
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.profile = QtWidgets.QWidget()
        self.profile.setStyleSheet("QWidget[objectName=\"profile\"] { background-color: #f0f8ff; border: none}")
        self.profile.setObjectName("profile")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.profile)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.profile)
        self.tabWidget_2.setStyleSheet("QTabWidget::pane {border: none; }\n"
"QTabWidget::tab-bar { alignment: left; position: absolute; }")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.information = QtWidgets.QWidget()
        self.information.setStyleSheet("QWidget[objectName=\"information\"] { background-color: #f0f8ff; }")
        self.information.setObjectName("information")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.information)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_6 = QtWidgets.QFrame(self.information)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("QFrame[objectName=\"frame_4\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 10, -1, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.image = QtWidgets.QLabel(self.frame_4)
        self.image.setStyleSheet("QLabel {\n"
"    border-radius: 75px;\n"
"    min-height: 150px;\n"
"    max-height: 150px;\n"
"    min-width: 150px;\n"
"    max-width: 150px;\n"
"    background-color: red;\n"
"}")
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.verticalLayout_5.addWidget(self.image)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fio = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fio.setFont(font)
        self.fio.setAlignment(QtCore.Qt.AlignCenter)
        self.fio.setObjectName("fio")
        self.verticalLayout_7.addWidget(self.fio)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_7)
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setStyleSheet("QFrame[objectName=\"frame\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.title.setFont(font)
        self.title.setStyleSheet("color: #7e7e7e;")
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 0, 180, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.group = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.group.setFont(font)
        self.group.setStyleSheet("background-color: #fcfcfc;")
        self.group.setObjectName("group")
        self.horizontalLayout_4.addWidget(self.group)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.birthday = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.birthday.setFont(font)
        self.birthday.setStyleSheet("background-color: #fcfcfc;")
        self.birthday.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.birthday.setObjectName("birthday")
        self.horizontalLayout_4.addWidget(self.birthday)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.profile_back = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.profile_back.setFont(font)
        self.profile_back.setStyleSheet("background-color: #fcfcfc;\n"
"min-width: 7em;\n"
"max-width: 10em;")
        self.profile_back.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profile_back.setObjectName("profile_back")
        self.horizontalLayout_4.addWidget(self.profile_back)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_16.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setStyleSheet("QFrame[objectName=\"frame_2\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.title_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("color: #7e7e7e")
        self.title_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout_5.addWidget(self.title_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 0, 150, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.institute = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.institute.setFont(font)
        self.institute.setStyleSheet("background-color: #fcfcfc;\n"
"min-width: 15em;\n"
"max-width: 15em;")
        self.institute.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.institute.setObjectName("institute")
        self.horizontalLayout_6.addWidget(self.institute)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.specialization = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.specialization.setFont(font)
        self.specialization.setStyleSheet("background-color: #fcfcfc;\n"
"min-width: 31.5em;\n"
"max-width: 31.5em;")
        self.specialization.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.specialization.setObjectName("specialization")
        self.horizontalLayout_6.addWidget(self.specialization)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_6)
        self.verticalLayout_16.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setStyleSheet("QFrame[objectName=\"frame_3\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.title_3.setFont(font)
        self.title_3.setStyleSheet("color: #7e7e7e")
        self.title_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_3.setObjectName("title_3")
        self.horizontalLayout_2.addWidget(self.title_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.email = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: #fcfcfc;\n"
"min-width: 25em;\n"
"max-width: 25em;")
        self.email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email.setObjectName("email")
        self.horizontalLayout.addWidget(self.email)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_18.addLayout(self.verticalLayout_3)
        self.verticalLayout_16.addWidget(self.frame_3)
        self.horizontalLayout_19.addWidget(self.frame_5)
        self.verticalLayout_15.addWidget(self.frame_6)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.tabWidget_2.addTab(self.information, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setStyleSheet("QWidget[objectName=\"settings\"] { background-color: #f0f8ff; }")
        self.settings.setObjectName("settings")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_17 = QtWidgets.QFrame(self.settings)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_16 = QtWidgets.QFrame(self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_13 = QtWidgets.QFrame(self.frame_16)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(12, -1, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.text_email = QtWidgets.QLabel(self.frame_13)
        self.text_email.setBaseSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.text_email.setFont(font)
        self.text_email.setStyleSheet("")
        self.text_email.setObjectName("text_email")
        self.horizontalLayout_24.addWidget(self.text_email)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem8)
        self.verticalLayout_20.addLayout(self.horizontalLayout_24)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(0, -1, 200, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.change_mail = QtWidgets.QLineEdit(self.frame_13)
        self.change_mail.setMaximumSize(QtCore.QSize(16777215, 43))
        self.change_mail.setStyleSheet("QLineEdit[objectName=\"change_mail\"] {\n"
"    min-height: 41px;\n"
"    max-height: 41px;\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 20px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 16px;\n"
"    padding-left: 1em;\n"
"}\n"
"")
        self.change_mail.setText("")
        self.change_mail.setObjectName("change_mail")
        self.verticalLayout_19.addWidget(self.change_mail)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.apply = QtWidgets.QPushButton(self.frame_13)
        self.apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply.setStyleSheet("QPushButton {\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"    min-weight: 0px;\n"
"    max-weight: 0px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #383838; \n"
"    background-color: #383838;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #616161;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #616161; \n"
"}")
        self.apply.setObjectName("apply")
        self.horizontalLayout_25.addWidget(self.apply)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        self.verticalLayout_25.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_16)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(12, -1, 0, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.text_passw_2 = QtWidgets.QLabel(self.frame_14)
        self.text_passw_2.setBaseSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_passw_2.setFont(font)
        self.text_passw_2.setStyleSheet("")
        self.text_passw_2.setObjectName("text_passw_2")
        self.horizontalLayout_26.addWidget(self.text_passw_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        self.verticalLayout_22.addLayout(self.horizontalLayout_26)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 200, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.change_passw = QtWidgets.QLineEdit(self.frame_14)
        self.change_passw.setMaximumSize(QtCore.QSize(16777215, 43))
        self.change_passw.setStyleSheet("QLineEdit[objectName=\"change_passw\"] {\n"
"    min-height: 41px;\n"
"    max-height: 41px;\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 20px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 16px;\n"
"    padding-left: 1em;\n"
"}\n"
"")
        self.change_passw.setText("")
        self.change_passw.setObjectName("change_passw")
        self.gridLayout.addWidget(self.change_passw, 0, 0, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.apply_2 = QtWidgets.QPushButton(self.frame_14)
        self.apply_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_2.setStyleSheet("QPushButton {\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"    min-weight: 0px;\n"
"    max-weight: 0px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #383838; \n"
"    background-color: #383838;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #616161;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #616161; \n"
"}")
        self.apply_2.setObjectName("apply_2")
        self.horizontalLayout_27.addWidget(self.apply_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem11)
        self.verticalLayout_22.addLayout(self.horizontalLayout_27)
        self.verticalLayout_25.addWidget(self.frame_14)
        self.horizontalLayout_29.addWidget(self.frame_16)
        self.frame_15 = QtWidgets.QFrame(self.frame_17)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.image_5 = QtWidgets.QLabel(self.frame_15)
        self.image_5.setStyleSheet("QLabel {\n"
"    border-radius: 90px;\n"
"    min-height: 180px;\n"
"    max-height: 180px;\n"
"    min-width: 180px;\n"
"    max-width: 180px;\n"
"    background-color: red;\n"
"}")
        self.image_5.setText("")
        self.image_5.setScaledContents(True)
        self.image_5.setAlignment(QtCore.Qt.AlignCenter)
        self.image_5.setObjectName("image_5")
        self.verticalLayout_23.addWidget(self.image_5)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.change = QtWidgets.QPushButton(self.frame_15)
        self.change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change.setStyleSheet("QPushButton {\n"
"    min-height: 31px;\n"
"    max-height: 31px;\n"
"    min-weight: 101px;\n"
"    max-weight: 101px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #383838; \n"
"    background-color: #383838;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #616161;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #616161; \n"
"}")
        self.change.setObjectName("change")
        self.horizontalLayout_28.addWidget(self.change)
        self.verticalLayout_24.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29.addWidget(self.frame_15)
        self.verticalLayout_11.addWidget(self.frame_17)
        self.frame_7 = QtWidgets.QFrame(self.settings)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.tabWidget_2.addTab(self.settings, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.profile, "")
        self.journal = QtWidgets.QWidget()
        self.journal.setStyleSheet("QWidget[objectName=\"journal\"] { background-color: #f0f8ff; }")
        self.journal.setObjectName("journal")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.journal)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_18 = QtWidgets.QFrame(self.journal)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(909, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.frame_8 = QtWidgets.QFrame(self.frame_18)
        self.frame_8.setStyleSheet("QFrame[objectName=\"frame_8\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.title_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.title_4.setFont(font)
        self.title_4.setStyleSheet("color: #7e7e7e;")
        self.title_4.setObjectName("title_4")
        self.verticalLayout_29.addWidget(self.title_4)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.date = QtWidgets.QLabel(self.frame_8)
        self.date.setObjectName("date")
        self.verticalLayout_31.addWidget(self.date)
        self.verticalLayout_30.addLayout(self.verticalLayout_31)
        self.horizontalLayout_10.addWidget(self.frame_8)
        self.verticalLayout_38.addWidget(self.frame_18)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem14)
        self.verticalLayout_38.addLayout(self.verticalLayout_37)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.frame_12 = QtWidgets.QFrame(self.journal)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_10 = QtWidgets.QFrame(self.frame_12)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setStyleSheet("QFrame[objectName=\"frame_9\"] {\n"
"    background-color: white;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_28.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.title_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.title_5.setFont(font)
        self.title_5.setStyleSheet("color: #7e7e7e;")
        self.title_5.setObjectName("title_5")
        self.verticalLayout_12.addWidget(self.title_5)
        self.verticalLayout_28.addLayout(self.verticalLayout_12)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.groupSelect = QtWidgets.QComboBox(self.frame_9)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.groupSelect.setFont(font)
        self.groupSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupSelect.setStyleSheet("QComboBox {\n"
"max-height: 20px;\n"
"min-height: 20px;\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 4px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(D:/courseworking/Project/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #black, stop: 1 #FFFFFF);\n"
" }")
        self.groupSelect.setObjectName("groupSelect")
        self.verticalLayout_26.addWidget(self.groupSelect)
        self.verticalLayout_28.addLayout(self.verticalLayout_26)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.title_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.title_6.setFont(font)
        self.title_6.setStyleSheet("color: #7e7e7e;")
        self.title_6.setObjectName("title_6")
        self.verticalLayout_13.addWidget(self.title_6)
        self.verticalLayout_28.addLayout(self.verticalLayout_13)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.semesterSelect = QtWidgets.QComboBox(self.frame_9)
        self.semesterSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.semesterSelect.setStyleSheet("QComboBox {\n"
"max-height: 20px;\n"
"min-height: 20px;\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 4px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(D:/courseworking/Project/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #black, stop: 1 #FFFFFF);\n"
" }")
        self.semesterSelect.setObjectName("semesterSelect")
        self.verticalLayout_27.addWidget(self.semesterSelect)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.title_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.title_7.setFont(font)
        self.title_7.setStyleSheet("color: #7e7e7e;")
        self.title_7.setObjectName("title_7")
        self.verticalLayout_14.addWidget(self.title_7)
        self.verticalLayout_28.addLayout(self.verticalLayout_14)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.subjectSelect = QtWidgets.QComboBox(self.frame_9)
        self.subjectSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subjectSelect.setStyleSheet("QComboBox {\n"
"max-height: 20px;\n"
"min-height: 20px;\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 4px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(D:/courseworking/Project/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #black, stop: 1 #FFFFFF);\n"
" }")
        self.subjectSelect.setObjectName("subjectSelect")
        self.verticalLayout_21.addWidget(self.subjectSelect)
        self.verticalLayout_28.addLayout(self.verticalLayout_21)
        self.verticalLayout_33.addWidget(self.frame_9)
        self.verticalLayout_35.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_12)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.pushButton = QtWidgets.QPushButton(self.frame_11)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    min-height: 21px;\n"
"    max-height: 21px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #383838; \n"
"    background-color: #383838;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #616161;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #616161; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_32.addWidget(self.pushButton)
        self.verticalLayout_34.addLayout(self.verticalLayout_32)
        self.verticalLayout_35.addWidget(self.frame_11)
        self.horizontalLayout_11.addWidget(self.frame_12)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_38.addLayout(self.horizontalLayout_11)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem17)
        self.verticalLayout_38.addLayout(self.verticalLayout_36)
        self.tabWidget.addTab(self.journal, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Main)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.fio.setText(_translate("Main", "Bashkov Denis"))
        self.title.setText(_translate("Main", "Личные данные"))
        self.group.setText(_translate("Main", "Группа: П2-19"))
        self.birthday.setText(_translate("Main", "Дата рождения:  23.09.2003"))
        self.profile_back.setText(_translate("Main", "Профиль: Нет"))
        self.title_2.setText(_translate("Main", "Корпоративные данные"))
        self.institute.setText(_translate("Main", "Институт: Программирование"))
        self.specialization.setText(_translate("Main", "Специальность: Программирование в компьютерных системах"))
        self.title_3.setText(_translate("Main", "Контакты"))
        self.email.setText(_translate("Main", "Адрес электронной почты: denis170.170@gmail.com"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.information), _translate("Main", "📊"))
        self.text_email.setText(_translate("Main", "Смена почты"))
        self.apply.setText(_translate("Main", "Применить"))
        self.text_passw_2.setText(_translate("Main", "Смена пароля"))
        self.apply_2.setText(_translate("Main", "Применить"))
        self.change.setText(_translate("Main", "Изменить"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.settings), _translate("Main", "⚙"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile), _translate("Main", "Профиль"))
        self.title_4.setText(_translate("Main", "Последнее время обновления данных"))
        self.date.setText(_translate("Main", "23.09.2003"))
        self.title_5.setText(_translate("Main", "Группа"))
        self.title_6.setText(_translate("Main", "Семестер"))
        self.title_7.setText(_translate("Main", "Предмет"))
        self.pushButton.setText(_translate("Main", "Открыть журнал успеваемости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.journal), _translate("Main", "Журнал"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
