# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_recovery_code.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recovery_2(object):
    def setupUi(self, Recovery_2):
        Recovery_2.setObjectName("Recovery_2")
        Recovery_2.resize(930, 190)
        Recovery_2.setMinimumSize(QtCore.QSize(930, 190))
        Recovery_2.setMaximumSize(QtCore.QSize(930, 190))
        Recovery_2.setStyleSheet("QWidget[objectName=\"Recovery_2\"] { background-color: #f6f7fb }")
        self.text_1 = QtWidgets.QLabel(Recovery_2)
        self.text_1.setGeometry(QtCore.QRect(20, 10, 901, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(99)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("font-weight: 800;\n"
"color: #383838;")
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QLabel(Recovery_2)
        self.text_2.setGeometry(QtCore.QRect(20, 40, 901, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("color: #6a6a6a;")
        self.text_2.setObjectName("text_2")
        self.code_email = QtWidgets.QLineEdit(Recovery_2)
        self.code_email.setGeometry(QtCore.QRect(20, 120, 751, 51))
        self.code_email.setStyleSheet("QLineEdit[objectName=\"code_email\"] {\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 15px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 17px;\n"
"    padding-left: 0.5em;\n"
"}\n"
"")
        self.code_email.setObjectName("code_email")
        self.apply = QtWidgets.QPushButton(Recovery_2)
        self.apply.setGeometry(QtCore.QRect(800, 130, 91, 31))
        self.apply.setMinimumSize(QtCore.QSize(91, 31))
        self.apply.setMaximumSize(QtCore.QSize(91, 31))
        self.apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \'SESans\',Arial,sans-serif;;    \n"
"    border: 1px solid #3f5cde; \n"
"    background-color: #3f5cde;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: #243581;    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 0px;\n"
"    background-color: #243581; \n"
"}")
        self.apply.setObjectName("apply")
        self.error = QtWidgets.QLabel(Recovery_2)
        self.error.setGeometry(QtCore.QRect(20, 69, 891, 41))
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")

        self.retranslateUi(Recovery_2)
        QtCore.QMetaObject.connectSlotsByName(Recovery_2)

    def retranslateUi(self, Recovery_2):
        _translate = QtCore.QCoreApplication.translate
        Recovery_2.setWindowTitle(_translate("Recovery_2", "Восстановление доступа"))
        self.text_1.setText(_translate("Recovery_2", "Восстановление доступа"))
        self.text_2.setText(_translate("Recovery_2", "Вам на почту отправлен код восстановления доступа, введите его в течение 10 минут."))
        self.code_email.setPlaceholderText(_translate("Recovery_2", "Введите код"))
        self.apply.setText(_translate("Recovery_2", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recovery_2 = QtWidgets.QWidget()
    ui = Ui_Recovery_2()
    ui.setupUi(Recovery_2)
    Recovery_2.show()
    sys.exit(app.exec_())
